### ISSUE TITLE
Erro sobre "split" no console

### ISSUE THREAD

**Issue by nathan-lucca** [WearifulCupid0/simple-discord-music-bot#1]
![image](https://user-images.githubusercontent.com/42450935/89739943-4869e500-da5b-11ea-8a9d-60bf056b8e07.png)

> Como arrumo esse erro?

**Comment by WearifulCupid0** [comment]
Hmm, tente filtrar dentro da estrutura da queue +- assim: if(this.duration == undefined) return;
acho que assim deve funcionar, o ponto é ele não retornaria a duração na música e pelo oque eu vi era na api em json que foi solicitado isso.

**Comment by nathan-lucca** [comment]
Certo!
